# Generated by Django 5.1.1 on 2024-09-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
    ]
