# Generated by Django 5.1.1 on 2024-09-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_middle_name_profile_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skills',
            new_name='name',
        ),
    ]
