# Generated by Django 5.1.1 on 2024-09-08 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_rename_skills_skills_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.job'),
            preserve_default=False,
        ),
    ]
