# Generated by Django 5.1.1 on 2024-09-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_remove_profile_job_job_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
