# Generated by Django 5.1.1 on 2024-09-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_profile_cv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
