# Generated by Django 5.1.1 on 2024-09-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_delete_alljob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='github',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
