# Generated by Django 5.1.1 on 2024-09-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('location', models.CharField(max_length=35)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('name_company', models.CharField(max_length=35)),
                ('description', models.TextField()),
            ],
        ),
    ]
