# Generated by Django 5.1.1 on 2024-09-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_remove_education_duration_remove_education_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='trac_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='role_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
