# Generated by Django 5.1.1 on 2024-09-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_education_trac_name_workexperience_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='role_name',
        ),
    ]
